sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 6
before_script:
  - npm prune
  - bower prune
install:
  - npm install -g bower
  - npm install -g phantomjs-prebuilt
  - npm install
  - bower install
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
